
#server:
#  port: 8080
#spring:
#  datasource:
#    driver-class-name: org.postgre.Driver
#    password: zhe1234
#    url: jdbc:postgresql://localhost:5432/postgre
#    username: postgre
#  profiles:
#    active: '@spring.profiles.active@'



# 服务端口
server:
  port: 8080
  servlet:
    context-path: /packageDataIO


#数据库配置
spring:
  profiles:
      active: '@spring.profiles.active@'
  datasource:
    
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: zhe1234
#    druid:
#      #初始化连接大小
#      initial-size: 8
#      #最小空闲连接数
#      min-idle: 5
#      #最大连接数
#      max-active: 10
#      #查询超时时间
#      query-timeout: 6000
#      #事务查询超时时间
#      transaction-query-timeout: 6000
#      #关闭空闲连接超时时间
#      remove-abandoned-timeout: 1800
#      filters: stat,config

#mybatis
mybatis:
  type-aliases-package: com.modelAndDomain
  mapper-locations: classpath:mybatis/mapper/*.xml



 